### ISSUE TITLE
[USER STORY] Attractions Eat and Drink

### ISSUE THREAD

**Issue by kalyanikommula** [CI-Stu/hogwarts-hackers#11]
As *a use*r, I want to* see places where I can eat/drink* so *I can determine if I want to eat and drink there.*

# Tasks:
- [x] Insert pictures of restaurants
- [x] Add rounded-corner edges
- [x] Add text for restaurants
- [x] Test responsiveness
