### ISSUE TITLE
[USER STORY] Location FAQS

### ISSUE THREAD

**Issue by kalyanikommula** [CI-Stu/hogwarts-hackers#17]
As *a site owner*, we want to *provide answers to the most often asked questions* so that *users have as much information as possible and also reduce further queries.* 

# Tasks:
- [x] create FAQS and add some useful information
- [x] add helpline contact
- [x] added some styles
- [x] Test responsiveness
