### ISSUE TITLE
[USER STORY] Location Transport Links

### ISSUE THREAD

**Issue by UsmanButt1** [CI-Stu/hogwarts-hackers#18]
As *a user*, I want *a list of various travel options including both car and public transport links* so that *users can plan their journey*

# Tasks:
- [x] Add transport images
- [x] Add some description about transport
- [x] Add styles to images
- [x] Test responsiveness
