### ISSUE TITLE
[USER STORY] Attractions Shops

### ISSUE THREAD

**Issue by UsmanButt1** [CI-Stu/hogwarts-hackers#7]
As *a user*, I want *to see a selection of retail outlets* so that *I can determine if I want to visit them*

# Tasks:
- [x] Insert pictures of shops
- [x] Add rounded-corner edges
- [x] Add text for shops
- [x] Test responsiveness
