### ISSUE TITLE
[USER STORY] Attractions Live Events

### ISSUE THREAD

**Issue by UsmanButt1** [CI-Stu/hogwarts-hackers#9]
As *a user* I want *to see a selection of landmarks and events* so that *I can determine if I want to visit them*

# Tasks:
- [x] Insert table
- [x] Add colour to match/suit the theme of the website
- [x] Input text for dates, fixtures and broom-off times
- [x] Make the table responsive
- [x] Test responsiveness
